<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;
use App\City;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		$now = Carbon::now('utc')->toDateTimeString();

		$data = array(
			array("province_id" => 1, "enname" => "Eshtehard", "faname" => "اشتهارد"),
			array("province_id" => 1, "enname" => "Fardis", "faname" => "فردیس"),
			array("province_id" => 1, "enname" => "Karaj", "faname" => "کرج"),
			array("province_id" => 1, "enname" => "Nazarabad", "faname" => "نظرآباد"),
			array("province_id" => 1, "enname" => "Savojbolagh", "faname" => "ساوجبلاغ"),
			array("province_id" => 1, "enname" => "Taleqan", "faname" => "طالقان"),

			array("province_id" => 2, "enname" => "Ardabil", "faname" => "اردبیل"),
			array("province_id" => 2, "enname" => "Bileh Savar", "faname" => "بیله‌سوار"),
			array("province_id" => 2, "enname" => "Germi", "faname" => "گرمی"),
			array("province_id" => 2, "enname" => "Khalkhal", "faname" => "خلخال"),
			array("province_id" => 2, "enname" => "Kowsar", "faname" => "کوثر"),
			array("province_id" => 2, "enname" => "Meshgin Shahr", "faname" => "مشگین شهر"),
			array("province_id" => 2, "enname" => "Namin", "faname" => "نمین"),
			array("province_id" => 2, "enname" => "Nir", "faname" => "نیر"),
			array("province_id" => 2, "enname" => "Parsabad", "faname" => "پارس‌آباد"),
			array("province_id" => 2, "enname" => "Sareyn", "faname" => "سرعین"),

			array("province_id" => 3, "enname" => "Asaluyeh", "faname" => "عسلویه"),
			array("province_id" => 3, "enname" => "Bushehr", "faname" => "بوشهر"),
			array("province_id" => 3, "enname" => "Dashtestan", "faname" => "دشتستان"),
			array("province_id" => 3, "enname" => "Dashti", "faname" => "دشتی"),
			array("province_id" => 3, "enname" => "Deyr", "faname" => "دیر"),
			array("province_id" => 3, "enname" => "Deylam", "faname" => "دیلم"),
			array("province_id" => 3, "enname" => "Ganaveh", "faname" => "گناوه"),
			array("province_id" => 3, "enname" => "Jam", "faname" => "جم"),
			array("province_id" => 3, "enname" => "Kangan", "faname" => "کنگان"),
			array("province_id" => 3, "enname" => "Tangestan", "faname" => "تنگستان"),

			array("province_id" => 4, "enname" => "Ardal", "faname" => "اردل"),
			array("province_id" => 4, "enname" => "Ben", "faname" => "بن"),
			array("province_id" => 4, "enname" => "Borujen", "faname" => "بروجن"),
			array("province_id" => 4, "enname" => "Farsan", "faname" => "فارسان"),
			array("province_id" => 4, "enname" => "Kiar", "faname" => "کیار"),
			array("province_id" => 4, "enname" => "Kuhrang", "faname" => "کوهرنگ"),
			array("province_id" => 4, "enname" => "Lordegan", "faname" => "لردگان"),
			array("province_id" => 4, "enname" => "Saman", "faname" => "سامان"),
			array("province_id" => 4, "enname" => "Shahrekord", "faname" => "شهرکرد"),

			array("province_id" => 5, "enname" => "Ahar", "faname" => "اهر"),
			array("province_id" => 5, "enname" => "Ajab Shir", "faname" => "عجب‌شیر"),
			array("province_id" => 5, "enname" => "Azarshahr", "faname" => "آذرشهر"),
			array("province_id" => 5, "enname" => "Bonab", "faname" => "بناب"),
			array("province_id" => 5, "enname" => "Bostanabad", "faname" => "بستان‌آباد"),
			array("province_id" => 5, "enname" => "Charuymaq", "faname" => "چاراویماق"),
			array("province_id" => 5, "enname" => "Heris", "faname" => "هریس"),
			array("province_id" => 5, "enname" => "Hashtrud", "faname" => "هشترود"),
			array("province_id" => 5, "enname" => "Jolfa", "faname" => "جلفا"),
			array("province_id" => 5, "enname" => "Kaleybar", "faname" => "کلیبر"),
			array("province_id" => 5, "enname" => "Khoda Afarin", "faname" => "خداآفرین"),
			array("province_id" => 5, "enname" => "Malekan", "faname" => "ملکان"),
			array("province_id" => 5, "enname" => "Maragheh", "faname" => "مراغه"),
			array("province_id" => 5, "enname" => "Marand", "faname" => "مرند"),
			array("province_id" => 5, "enname" => "Mianeh", "faname" => "میانه"),
			array("province_id" => 5, "enname" => "Osku", "faname" => "اسکو"),
			array("province_id" => 5, "enname" => "Sarab", "faname" => "سراب"),
			array("province_id" => 5, "enname" => "Shabestar", "faname" => "شبستر"),
			array("province_id" => 5, "enname" => "Tabriz", "faname" => "تبریز"),
			array("province_id" => 5, "enname" => "Varzaqan", "faname" => "ورزقان"),

			array("province_id" => 6, "enname" => "Aran and Bidgol", "faname" => "آران و بیدگل"),
			array("province_id" => 6, "enname" => "Ardestan", "faname" => "اردستان"),
			array("province_id" => 6, "enname" => "Borkhar", "faname" => "برخوار"),
			array("province_id" => 6, "enname" => "Bouein and Miandasht", "faname" => "بوئین و میاندشت"),
			array("province_id" => 6, "enname" => "Chadegan", "faname" => "چادگان"),
			array("province_id" => 6, "enname" => "Dehaqan", "faname" => "دهاقان"),
			array("province_id" => 6, "enname" => "Falavarjan", "faname" => "فلاورجان"),
			array("province_id" => 6, "enname" => "Fereydan", "faname" => "فریدن"),
			array("province_id" => 6, "enname" => "Fereydunshahr", "faname" => "فریدون‌شهر"),
			array("province_id" => 6, "enname" => "Golpayegan", "faname" => "گلپایگان"),
			array("province_id" => 6, "enname" => "Isfahan", "faname" => "اصفهان"),
			array("province_id" => 6, "enname" => "Kashan", "faname" => "کاشان"),
			array("province_id" => 6, "enname" => "Khour and Biabanak", "faname" => "خور و بیابانک"),
			array("province_id" => 6, "enname" => "Khvansar", "faname" => "خوانسار"),
			array("province_id" => 6, "enname" => "Khomeyni Shahr", "faname" => "خمینی‌شهر"),
			array("province_id" => 6, "enname" => "Lenjan", "faname" => "لنجان"),
			array("province_id" => 6, "enname" => "Mobarakeh", "faname" => "مبارکه"),
			array("province_id" => 6, "enname" => "Nain", "faname" => "نائین"),
			array("province_id" => 6, "enname" => "Najafabad", "faname" => "نجف‌آباد"),
			array("province_id" => 6, "enname" => "Natanz", "faname" => "نطنز"),
			array("province_id" => 6, "enname" => "Semirom", "faname" => "سمیرم"),
			array("province_id" => 6, "enname" => "Shahreza", "faname" => "شهرضا"),
			array("province_id" => 6, "enname" => "Shahin Shahr and Meymeh", "faname" => "شاهین‌شهر و میمه"),
			array("province_id" => 6, "enname" => "Tiran and Karvan", "faname" => "تیران و کرون"),

			array("province_id" => 7, "enname" => "Abadeh", "faname" => "آباده"),
			array("province_id" => 7, "enname" => "Arsanjan", "faname" => "ارسنجان"),
			array("province_id" => 7, "enname" => "Bavanat", "faname" => "بوانات"),
			array("province_id" => 7, "enname" => "Darab", "faname" => "داراب"),
			array("province_id" => 7, "enname" => "Eqlid", "faname" => "اقلید"),
			array("province_id" => 7, "enname" => "Estahban", "faname" => "استهبان"),
			array("province_id" => 7, "enname" => "Farashband", "faname" => "فراشبند"),
			array("province_id" => 7, "enname" => "Fasa", "faname" => "فسا"),
			array("province_id" => 7, "enname" => "Firuzabad", "faname" => "فیروزآباد"),
			array("province_id" => 7, "enname" => "Gerash", "faname" => "گراش"),
			array("province_id" => 7, "enname" => "Jahrom", "faname" => "جهرم"),
			array("province_id" => 7, "enname" => "Kavar", "faname" => "کوار"),
			array("province_id" => 7, "enname" => "Kazerun", "faname" => "کازرون"),
			array("province_id" => 7, "enname" => "Kharameh", "faname" => "خرامه"),
			array("province_id" => 7, "enname" => "Khonj", "faname" => "خنج"),
			array("province_id" => 7, "enname" => "Khorrambid", "faname" => "خرم‌بید"),
			array("province_id" => 7, "enname" => "Lamerd", "faname" => "لامرد"),
			array("province_id" => 7, "enname" => "Larestan", "faname" => "لارستان"),
			array("province_id" => 7, "enname" => "Mamasani", "faname" => "ممسنی"),
			array("province_id" => 7, "enname" => "Marvdasht", "faname" => "مرودشت"),
			array("province_id" => 7, "enname" => "Mohr", "faname" => "مهر"),
			array("province_id" => 7, "enname" => "Neyriz", "faname" => "نی ریز"),
			array("province_id" => 7, "enname" => "Pasargad", "faname" => "پاسارگاد"),
			array("province_id" => 7, "enname" => "Qir and Karzin", "faname" => "قیر و کارزین"),
			array("province_id" => 7, "enname" => "Rostam", "faname" => "رستم"),
			array("province_id" => 7, "enname" => "Sarvestan", "faname" => "سروستان"),
			array("province_id" => 7, "enname" => "Sepidan", "faname" => "سپیدان"),
			array("province_id" => 7, "enname" => "Shiraz", "faname" => "شیراز"),
			array("province_id" => 7, "enname" => "Zarrin Dasht", "faname" => "زرین‌دشت"),

			array("province_id" => 8, "enname" => "Amlash", "faname" => "املش"),
			array("province_id" => 8, "enname" => "Astara", "faname" => "آستارا"),
			array("province_id" => 8, "enname" => "Astaneh ye Ashrafiyeh", "faname" => "آستانه اشرفیه"),
			array("province_id" => 8, "enname" => "Bandar e Anzali", "faname" => "بندر انزلی"),
			array("province_id" => 8, "enname" => "Fuman", "faname" => "فومن"),
			array("province_id" => 8, "enname" => "Lahijan", "faname" => "لاهیجان"),
			array("province_id" => 8, "enname" => "Langarud", "faname" => "لنگرود"),
			array("province_id" => 8, "enname" => "Masal", "faname" => "ماسال"),
			array("province_id" => 8, "enname" => "Rasht", "faname" => "رشت"),
			array("province_id" => 8, "enname" => "Rezvanshahr", "faname" => "رضوانشهر"),
			array("province_id" => 8, "enname" => "Rudbar", "faname" => "رودبار"),
			array("province_id" => 8, "enname" => "Rudsar", "faname" => "رودسر"),
			array("province_id" => 8, "enname" => "Shaft", "faname" => "شفت"),
			array("province_id" => 8, "enname" => "Siahkal", "faname" => "سیاهکل"),
			array("province_id" => 8, "enname" => "Sowme'eh Sara", "faname" => "صومعه‌سرا"),
			array("province_id" => 8, "enname" => "Talesh", "faname" => "طوالش"),

			array("province_id" => 9, "enname" => "Aliabad", "faname" => "علی‌آباد"),
			array("province_id" => 9, "enname" => "Aqqala", "faname" => "آق‌قلا"),
			array("province_id" => 9, "enname" => "Azadshahr", "faname" => "آزادشهر"),
			array("province_id" => 9, "enname" => "Bandar e Gaz", "faname" => "بندر گز"),
			array("province_id" => 9, "enname" => "Galikash", "faname" => "گالیکش"),
			array("province_id" => 9, "enname" => "Gomishan", "faname" => "گمیشان"),
			array("province_id" => 9, "enname" => "Gonbad e Kavus", "faname" => "گنبد کاووس"),
			array("province_id" => 9, "enname" => "Gorgan", "faname" => "گرگان"),
			array("province_id" => 9, "enname" => "Kalaleh", "faname" => "کلاله"),
			array("province_id" => 9, "enname" => "Kordkuy", "faname" => "کردکوی"),
			array("province_id" => 9, "enname" => "Maraveh Tappeh", "faname" => "مراوه‌تپه"),
			array("province_id" => 9, "enname" => "Minudasht", "faname" => "مینودشت"),
			array("province_id" => 9, "enname" => "Ramian", "faname" => "رامیان"),
			array("province_id" => 9, "enname" => "Torkaman", "faname" => "ترکمن"),

			array("province_id" => 10, "enname" => "Asadabad", "faname" => "اسدآباد"),
			array("province_id" => 10, "enname" => "Bahar", "faname" => "بهار"),
			array("province_id" => 10, "enname" => "Famenin", "faname" => "فامنین"),
			array("province_id" => 10, "enname" => "Hamadan", "faname" => "همدان"),
			array("province_id" => 10, "enname" => "Kabudarahang", "faname" => "کبودرآهنگ"),
			array("province_id" => 10, "enname" => "Malayer", "faname" => "ملایر"),
			array("province_id" => 10, "enname" => "Nahavand", "faname" => "نهاوند"),
			array("province_id" => 10, "enname" => "Razan", "faname" => "رزن"),
			array("province_id" => 10, "enname" => "Tuyserkan", "faname" => "تویسرکان"),

			array("province_id" => 11, "enname" => "Abumusa", "faname" => "ابوموسی"),
			array("province_id" => 11, "enname" => "Bandar Abbas", "faname" => "بندرعباس"),
			array("province_id" => 11, "enname" => "Bandar Lengeh", "faname" => "بندر لنگه"),
			array("province_id" => 11, "enname" => "Bashagard", "faname" => "بشاگرد"),
			array("province_id" => 11, "enname" => "Bastak", "faname" => "بستک"),
			array("province_id" => 11, "enname" => "Hajjiabad", "faname" => "حاجی‌آباد"),
			array("province_id" => 11, "enname" => "Jask", "faname" => "جاسک"),
			array("province_id" => 11, "enname" => "Khamir", "faname" => "خمیر"),
			array("province_id" => 11, "enname" => "Minab", "faname" => "میناب"),
			array("province_id" => 11, "enname" => "Parsian", "faname" => "پارسیان"),
			array("province_id" => 11, "enname" => "Qeshm", "faname" => "قشم"),
			array("province_id" => 11, "enname" => "Rudan", "faname" => "رودان"),
			array("province_id" => 11, "enname" => "Sirik", "faname" => "سیریک"),

			array("province_id" => 12, "enname" => "Abdanan", "faname" => "آبدانان"),
			array("province_id" => 12, "enname" => "Badreh", "faname" => "بدره"),
			array("province_id" => 12, "enname" => "Darreh Shahr", "faname" => "دره‌شهر"),
			array("province_id" => 12, "enname" => "Dehloran", "faname" => "دهلران"),
			array("province_id" => 12, "enname" => "Eyvan", "faname" => "ایوان"),
			array("province_id" => 12, "enname" => "Ilam", "faname" => "ایلام"),
			array("province_id" => 12, "enname" => "Malekshahi", "faname" => "ملکشاهی"),
			array("province_id" => 12, "enname" => "Mehran", "faname" => "مهران"),
			array("province_id" => 12, "enname" => "Chardavol", "faname" => "چرداول"),
			array("province_id" => 12, "enname" => "Sirvan", "faname" => "سیروان"),

			array("province_id" => 13, "enname" => "Anar", "faname" => "انار"),
			array("province_id" => 13, "enname" => "Anbarabad", "faname" => "عنبرآباد"),
			array("province_id" => 13, "enname" => "Arzuiyeh", "faname" => "ارزوئیه"),
			array("province_id" => 13, "enname" => "Baft", "faname" => "بافت"),
			array("province_id" => 13, "enname" => "Bam", "faname" => "بم"),
			array("province_id" => 13, "enname" => "Bardsir", "faname" => "بردسیر"),
			array("province_id" => 13, "enname" => "Fahraj", "faname" => "فهرج"),
			array("province_id" => 13, "enname" => "Faryab", "faname" => "فاریاب"),
			array("province_id" => 13, "enname" => "Jiroft", "faname" => "جیرفت"),
			array("province_id" => 13, "enname" => "Kahnuj", "faname" => "کهنوج"),
			array("province_id" => 13, "enname" => "Kerman", "faname" => "کرمان"),
			array("province_id" => 13, "enname" => "Kuhbanan", "faname" => "کوهبنان"),
			array("province_id" => 13, "enname" => "Manujan", "faname" => "منوجان"),
			array("province_id" => 13, "enname" => "Narmashir", "faname" => "نرماشیر"),
			array("province_id" => 13, "enname" => "Qaleh Ganj", "faname" => "قلعه گنج"),
			array("province_id" => 13, "enname" => "Rabor", "faname" => "رابر"),
			array("province_id" => 13, "enname" => "Rafsanjan", "faname" => "رفسنجان"),
			array("province_id" => 13, "enname" => "Ravar", "faname" => "راور"),
			array("province_id" => 13, "enname" => "Rigan", "faname" => "ریگان"),
			array("province_id" => 13, "enname" => "Rudbar e Jonubi", "faname" => "رودبار جنوب"),
			array("province_id" => 13, "enname" => "Shahr e Babak", "faname" => "شهربابک"),
			array("province_id" => 13, "enname" => "Sirjan", "faname" => "سیرجان"),
			array("province_id" => 13, "enname" => "Zarand", "faname" => "زرند"),

			array("province_id" => 14, "enname" => "Dalahu", "faname" => "دالاهو"),
			array("province_id" => 14, "enname" => "Eslamabad e Gharb", "faname" => "اسلام‌آباد غرب"),
			array("province_id" => 14, "enname" => "Gilan e Gharb", "faname" => "گیلانغرب"),
			array("province_id" => 14, "enname" => "Harsin", "faname" => "هرسین"),
			array("province_id" => 14, "enname" => "Javanrud", "faname" => "جوانرود"),
			array("province_id" => 14, "enname" => "Kangavar", "faname" => "کنگاور"),
			array("province_id" => 14, "enname" => "Kermanshah", "faname" => "کرمانشاه"),
			array("province_id" => 14, "enname" => "Paveh", "faname" => "پاوه"),
			array("province_id" => 14, "enname" => "Qasr e Shirin", "faname" => "قصرشیرین"),
			array("province_id" => 14, "enname" => "Ravansar", "faname" => "روانسر"),
			array("province_id" => 14, "enname" => "Sahneh", "faname" => "صحنه"),
			array("province_id" => 14, "enname" => "Sarpol e Zahab", "faname" => "سرپل ذهاب"),
			array("province_id" => 14, "enname" => "Salas e Babajani", "faname" => "ثلاث باباجانی"),
			array("province_id" => 14, "enname" => "Sonqor", "faname" => "سنقر"),

			array("province_id" => 15, "enname" => "Abadan", "faname" => "آبادان"),
			array("province_id" => 15, "enname" => "Aghajari", "faname" => "آغاجاری"),
			array("province_id" => 15, "enname" => "Ahvaz", "faname" => "اهواز"),
			array("province_id" => 15, "enname" => "Andika", "faname" => "اندیکا"),
			array("province_id" => 15, "enname" => "Andimeshk", "faname" => "اندیمشک"),
			array("province_id" => 15, "enname" => "Bagh e Malek", "faname" => "باغ‌ملک"),
			array("province_id" => 15, "enname" => "Bavi", "faname" => "باوی"),
			array("province_id" => 15, "enname" => "Behbahan", "faname" => "بهبهان"),
			array("province_id" => 15, "enname" => "Dasht e Azadegan", "faname" => "دشت آزادگان"),
			array("province_id" => 15, "enname" => "Dezful", "faname" => "دزفول"),
			array("province_id" => 15, "enname" => "Gotvand", "faname" => "گتوند"),
			array("province_id" => 15, "enname" => "Haftkel", "faname" => "هفتکل"),
			array("province_id" => 15, "enname" => "Hamidieh", "faname" => "حمیدیه"),
			array("province_id" => 15, "enname" => "Hendijan", "faname" => "هندیجان"),
			array("province_id" => 15, "enname" => "Hoveyzeh", "faname" => "هویزه"),
			array("province_id" => 15, "enname" => "Izeh", "faname" => "ایذه"),
			array("province_id" => 15, "enname" => "Karun", "faname" => "کارون"),
			array("province_id" => 15, "enname" => "Khorramshahr", "faname" => "خرمشهر"),
			array("province_id" => 15, "enname" => "Lali", "faname" => "لالی"),
			array("province_id" => 15, "enname" => "Mahshahr", "faname" => "ماهشهر"),
			array("province_id" => 15, "enname" => "Masjed Soleyman", "faname" => "مسجدسلیمان"),
			array("province_id" => 15, "enname" => "Omidiyeh", "faname" => "امیدیه"),
			array("province_id" => 15, "enname" => "Ramhormoz", "faname" => "رامهرمز"),
			array("province_id" => 15, "enname" => "Ramshir", "faname" => "رامشیر"),
			array("province_id" => 15, "enname" => "Shadegan", "faname" => "شادگان"),
			array("province_id" => 15, "enname" => "Shush", "faname" => "شوش"),
			array("province_id" => 15, "enname" => "Shushtar", "faname" => "شوشتر"),

			array("province_id" => 16, "enname" => "Basht", "faname" => "باشت"),
			array("province_id" => 16, "enname" => "Bahmai", "faname" => "بهمئی"),
			array("province_id" => 16, "enname" => "Boyer Ahmad", "faname" => "بویراحمد"),
			array("province_id" => 16, "enname" => "Charam", "faname" => "چرام"),
			array("province_id" => 16, "enname" => "Dana", "faname" => "دنا"),
			array("province_id" => 16, "enname" => "Gachsaran", "faname" => "گچساران"),
			array("province_id" => 16, "enname" => "Kohgiluyeh", "faname" => "کهگیلویه"),
			array("province_id" => 16, "enname" => "Landeh", "faname" => "لنده"),

			array("province_id" => 17, "enname" => "Baneh", "faname" => "بانه"),
			array("province_id" => 17, "enname" => "Bijar", "faname" => "بیجار"),
			array("province_id" => 17, "enname" => "Dehgolan", "faname" => "دهگلان"),
			array("province_id" => 17, "enname" => "Divandarreh", "faname" => "دیواندره"),
			array("province_id" => 17, "enname" => "Kamyaran", "faname" => "کامیاران"),
			array("province_id" => 17, "enname" => "Marivan", "faname" => "مریوان"),
			array("province_id" => 17, "enname" => "Qorveh", "faname" => "قروه"),
			array("province_id" => 17, "enname" => "Sanandaj", "faname" => "سنندج"),
			array("province_id" => 17, "enname" => "Saqqez", "faname" => "سقز"),
			array("province_id" => 17, "enname" => "Sarvabad", "faname" => "سروآباد"),

			array("province_id" => 18, "enname" => "Aligudarz", "faname" => "الیگودرز"),
			array("province_id" => 18, "enname" => "Azna", "faname" => "ازنا"),
			array("province_id" => 18, "enname" => "Borujerd", "faname" => "بروجرد"),
			array("province_id" => 18, "enname" => "Delfan", "faname" => "دلفان"),
			array("province_id" => 18, "enname" => "Dorud", "faname" => "دورود"),
			array("province_id" => 18, "enname" => "Dowreh", "faname" => "دوره"),
			array("province_id" => 18, "enname" => "Khorramabad", "faname" => "خرم‌آباد"),
			array("province_id" => 18, "enname" => "Kuhdasht", "faname" => "کوهدشت"),
			array("province_id" => 18, "enname" => "Pol e Dokhtar", "faname" => "پلدختر"),
			array("province_id" => 18, "enname" => "Rumeshkan", "faname" => "رومشکان"),
			array("province_id" => 18, "enname" => "Selseleh", "faname" => "سلسله"),

			array("province_id" => 19, "enname" => "Ashtian", "faname" => "آشتیان"),
			array("province_id" => 19, "enname" => "Arak", "faname" => "اراک"),
			array("province_id" => 19, "enname" => "Delijan", "faname" => "دلیجان"),
			array("province_id" => 19, "enname" => "Farahan", "faname" => "فراهان"),
			array("province_id" => 19, "enname" => "Khomeyn", "faname" => "خمین"),
			array("province_id" => 19, "enname" => "Khondab", "faname" => "خنداب"),
			array("province_id" => 19, "enname" => "Komijan", "faname" => "کمیجان"),
			array("province_id" => 19, "enname" => "Mahallat", "faname" => "محلات"),
			array("province_id" => 19, "enname" => "Saveh", "faname" => "ساوه"),
			array("province_id" => 19, "enname" => "Shazand", "faname" => "شازند"),
			array("province_id" => 19, "enname" => "Tafresh", "faname" => "تفرش"),
			array("province_id" => 19, "enname" => "Zarandieh", "faname" => "زرندیه"),

			array("province_id" => 20, "enname" => "Abbasabad", "faname" => "عباس‌آباد"),
			array("province_id" => 20, "enname" => "Amol", "faname" => "آمل"),
			array("province_id" => 20, "enname" => "Babol", "faname" => "بابل"),
			array("province_id" => 20, "enname" => "Babolsar", "faname" => "بابلسر"),
			array("province_id" => 20, "enname" => "Behshahr", "faname" => "بهشهر"),
			array("province_id" => 20, "enname" => "Chalus", "faname" => "چالوس"),
			array("province_id" => 20, "enname" => "Fereydunkenar", "faname" => "فریدونکنار"),
			array("province_id" => 20, "enname" => "Galugah", "faname" => "گلوگاه"),
			array("province_id" => 20, "enname" => "Juybar", "faname" => "جویبار"),
			array("province_id" => 20, "enname" => "Kelardasht", "faname" => "کلاردشت"),
			array("province_id" => 20, "enname" => "Mahmudabad", "faname" => "محمودآباد"),
			array("province_id" => 20, "enname" => "Miandorud", "faname" => "میاندرود"),
			array("province_id" => 20, "enname" => "Neka", "faname" => "نکا"),
			array("province_id" => 20, "enname" => "Nowshahr", "faname" => "نوشهر"),
			array("province_id" => 20, "enname" => "Nur", "faname" => "نور"),
			array("province_id" => 20, "enname" => "Qaem Shahr", "faname" => "قائم‌شهر"),
			array("province_id" => 20, "enname" => "Ramsar", "faname" => "رامسر"),
			array("province_id" => 20, "enname" => "Sari", "faname" => "ساری"),
			array("province_id" => 20, "enname" => "Simorgh", "faname" => "سیمرغ"),
			array("province_id" => 20, "enname" => "North Savadkuh", "faname" => "سوادکوه"),
			array("province_id" => 20, "enname" => "Savadkuh", "faname" => "سوادکوه شمالی"),
			array("province_id" => 20, "enname" => "Tonekabon", "faname" => "تنکابن"),

			array("province_id" => 21, "enname" => "Bojnord", "faname" => "بجنورد"),
			array("province_id" => 21, "enname" => "Esfarayen", "faname" => "اسفراین"),
			array("province_id" => 21, "enname" => "Faruj", "faname" => "فاروج"),
			array("province_id" => 21, "enname" => "Garmeh", "faname" => "گرمه"),
			array("province_id" => 21, "enname" => "Jajarm", "faname" => "جاجرم"),
			array("province_id" => 21, "enname" => "Maneh and Samalqan", "faname" => "مانه و سملقان"),
			array("province_id" => 21, "enname" => "Raz and Jargalan", "faname" => "راز و جرگلان"),
			array("province_id" => 21, "enname" => "Shirvan", "faname" => "شیروان"),

			array("province_id" => 22, "enname" => "Abyek", "faname" => "آبیک"),
			array("province_id" => 22, "enname" => "Avaj", "faname" => "آوج"),
			array("province_id" => 22, "enname" => "Alborz", "faname" => "البرز"),
			array("province_id" => 22, "enname" => "Buin Zahra", "faname" => "بوئین‌زهرا"),
			array("province_id" => 22, "enname" => "Qazvin", "faname" => "قزوین"),
			array("province_id" => 22, "enname" => "Takestan", "faname" => "تاکستان"),

			array("province_id" => 23, "enname" => "Qom", "faname" => "قم"),

			array("province_id" => 24, "enname" => "Bajestan", "faname" => "بجستان"),
			array("province_id" => 24, "enname" => "Bakharz", "faname" => "باخرز"),
			array("province_id" => 24, "enname" => "Bardaskan", "faname" => "بردسکن"),
			array("province_id" => 24, "enname" => "Chenaran", "faname" => "چناران"),
			array("province_id" => 24, "enname" => "Dargaz", "faname" => "درگز"),
			array("province_id" => 24, "enname" => "Davarzan", "faname" => "داورزن"),
			array("province_id" => 24, "enname" => "Fariman", "faname" => "فریمان"),
			array("province_id" => 24, "enname" => "Firuzeh", "faname" => "فیروزه"),
			array("province_id" => 24, "enname" => "Gonabad", "faname" => "گناباد"),
			array("province_id" => 24, "enname" => "Jowayin", "faname" => "جوین"),
			array("province_id" => 24, "enname" => "Joghatai", "faname" => "جغتای"),
			array("province_id" => 24, "enname" => "Kalat", "faname" => "کلات"),
			array("province_id" => 24, "enname" => "Kashmar", "faname" => "کاشمر"),
			array("province_id" => 24, "enname" => "Khaf", "faname" => "خواف"),
			array("province_id" => 24, "enname" => "Khalilabad", "faname" => "خلیل‌آباد"),
			array("province_id" => 24, "enname" => "Khoshab", "faname" => "خوشاب"),
			array("province_id" => 24, "enname" => "Mahvelat", "faname" => "مه‌ولات"),
			array("province_id" => 24, "enname" => "Mashhad", "faname" => "مشهد"),
			array("province_id" => 24, "enname" => "Nishapur", "faname" => "نیشابور"),
			array("province_id" => 24, "enname" => "Quchan", "faname" => "قوچان"),
			array("province_id" => 24, "enname" => "Roshtkhar", "faname" => "رشتخوار"),
			array("province_id" => 24, "enname" => "Sabzevar", "faname" => "سبزوار"),
			array("province_id" => 24, "enname" => "Sarakhs", "faname" => "سرخس"),
			array("province_id" => 24, "enname" => "Taybad", "faname" => "تایباد"),
			array("province_id" => 24, "enname" => "Binalud", "faname" => "بینالود"),
			array("province_id" => 24, "enname" => "Torbat e Jam", "faname" => "تربت جام"),
			array("province_id" => 24, "enname" => "Torbat e Heydarieh", "faname" => "تربت حیدریه"),
			array("province_id" => 24, "enname" => "Zaveh", "faname" => "زاوه"),

			array("province_id" => 25, "enname" => "Aradan", "faname" => "آرادان"),
			array("province_id" => 25, "enname" => "Damghan", "faname" => "دامغان"),
			array("province_id" => 25, "enname" => "Garmsar", "faname" => "گرمسار"),
			array("province_id" => 25, "enname" => "Mehdishahr", "faname" => "مهدی‌شهر"),
			array("province_id" => 25, "enname" => "Meyami", "faname" => "میامی"),
			array("province_id" => 25, "enname" => "Semnan", "faname" => "سمنان"),
			array("province_id" => 25, "enname" => "Shahrud", "faname" => "شاهرود"),
			array("province_id" => 25, "enname" => "Sorkheh", "faname" => "سرخه"),

			array("province_id" => 26, "enname" => "Chabahar", "faname" => "چابهار"),
			array("province_id" => 26, "enname" => "Dalgan", "faname" => "دلگان"),
			array("province_id" => 26, "enname" => "Fanuj", "faname" => "فنوج"),
			array("province_id" => 26, "enname" => "Hamun", "faname" => "هامون"),
			array("province_id" => 26, "enname" => "Hirmand", "faname" => "هیرمند"),
			array("province_id" => 26, "enname" => "Iranshahr", "faname" => "ایرانشهر"),
			array("province_id" => 26, "enname" => "Khash", "faname" => "خاش"),
			array("province_id" => 26, "enname" => "Konarak", "faname" => "کنارک"),
			array("province_id" => 26, "enname" => "Mehrestan", "faname" => "مهرستان"),
			array("province_id" => 26, "enname" => "Mirjaveh", "faname" => "میرجاوه"),
			array("province_id" => 26, "enname" => "Nik Shahr", "faname" => "نیک شهر"),
			array("province_id" => 26, "enname" => "Nimruz", "faname" => "نیمروز"),
			array("province_id" => 26, "enname" => "Qasr e Qand", "faname" => "قصرقند"),
			array("province_id" => 26, "enname" => "Saravan", "faname" => "سراوان"),
			array("province_id" => 26, "enname" => "Sarbaz", "faname" => "سرباز"),
			array("province_id" => 26, "enname" => "Sib and Suran", "faname" => "سیب و سوران"),
			array("province_id" => 26, "enname" => "Zabol", "faname" => "زابل"),
			array("province_id" => 26, "enname" => "Zahedan", "faname" => "زاهدان"),
			array("province_id" => 26, "enname" => "Zehak", "faname" => "زهک"),

			array("province_id" => 27, "enname" => "Birjand", "faname" => "بیرجند"),
			array("province_id" => 27, "enname" => "Boshruyeh", "faname" => "بشرویه"),
			array("province_id" => 27, "enname" => "Darmian", "faname" => "درمیان"),
			array("province_id" => 27, "enname" => "Ferdows", "faname" => "فردوس"),
			array("province_id" => 27, "enname" => "Khusf", "faname" => "خوسف"),
			array("province_id" => 27, "enname" => "Nehbandan", "faname" => "نهبندان"),
			array("province_id" => 27, "enname" => "Qaenat", "faname" => "قائنات"),
			array("province_id" => 27, "enname" => "Sarayan", "faname" => "سرایان"),
			array("province_id" => 27, "enname" => "Sarbisheh", "faname" => "سربیشه"),
			array("province_id" => 27, "enname" => "Tabas", "faname" => "طبس"),
			array("province_id" => 27, "enname" => "Zirkuh", "faname" => "زیرکوه"),

			array("province_id" => 28, "enname" => "Baharestan", "faname" => "بهارستان"),
			array("province_id" => 28, "enname" => "Damavand", "faname" => "دماوند"),
			array("province_id" => 28, "enname" => "Eslamshahr", "faname" => "اسلامشهر"),
			array("province_id" => 28, "enname" => "Firuzkuh", "faname" => "فیروزکوه"),
			array("province_id" => 28, "enname" => "Malard", "faname" => "ملارد"),
			array("province_id" => 28, "enname" => "Pakdasht", "faname" => "پاکدشت"),
			array("province_id" => 28, "enname" => "Pardis", "faname" => "پردیس"),
			array("province_id" => 28, "enname" => "Pishva", "faname" => "پیشوا"),
			array("province_id" => 28, "enname" => "Robat Karim", "faname" => "رباط‌کریم"),
			array("province_id" => 28, "enname" => "Rey", "faname" => "ری"),
			array("province_id" => 28, "enname" => "Shemiranat", "faname" => "شمیرانات"),
			array("province_id" => 28, "enname" => "Shahriar", "faname" => "شهریار"),
			array("province_id" => 28, "enname" => "Qarchak", "faname" => "قرچک"),
			array("province_id" => 28, "enname" => "Qods", "faname" => "قدس"),
			array("province_id" => 28, "enname" => "Tehran", "faname" => "تهران"),
			array("province_id" => 28, "enname" => "Varamin", "faname" => "ورامین"),

			array("province_id" => 29, "enname" => "Bukan", "faname" => "بوکان"),
			array("province_id" => 29, "enname" => "Chaldoran", "faname" => "چالدران"),
			array("province_id" => 29, "enname" => "Chaypareh", "faname" => "چایپاره"),
			array("province_id" => 29, "enname" => "Khoy", "faname" => "خوی"),
			array("province_id" => 29, "enname" => "Mahabad", "faname" => "مهاباد"),
			array("province_id" => 29, "enname" => "Maku", "faname" => "ماکو"),
			array("province_id" => 29, "enname" => "Miandoab", "faname" => "میاندوآب"),
			array("province_id" => 29, "enname" => "Naqadeh", "faname" => "نقده"),
			array("province_id" => 29, "enname" => "Oshnavieh", "faname" => "اشنویه"),
			array("province_id" => 29, "enname" => "Piranshahr", "faname" => "پیرانشهر"),
			array("province_id" => 29, "enname" => "Poldasht", "faname" => "پلدشت"),
			array("province_id" => 29, "enname" => "Salmas", "faname" => "سلماس"),
			array("province_id" => 29, "enname" => "Sardasht", "faname" => "سردشت"),
			array("province_id" => 29, "enname" => "Shahin Dezh", "faname" => "شاهین‌دژ"),
			array("province_id" => 29, "enname" => "Showt", "faname" => "شوط"),
			array("province_id" => 29, "enname" => "Takab", "faname" => "تکاب"),
			array("province_id" => 29, "enname" => "Urmia", "faname" => "ارومیه"),

			array("province_id" => 30, "enname" => "Abarkuh", "faname" => "ابرکوه"),
			array("province_id" => 30, "enname" => "Ardakan", "faname" => "اردکان"),
			array("province_id" => 30, "enname" => "Ashkezar", "faname" => "اشکذر"),
			array("province_id" => 30, "enname" => "Bafq", "faname" => "بافق"),
			array("province_id" => 30, "enname" => "Behabad", "faname" => "بهاباد"),
			array("province_id" => 30, "enname" => "Khatam", "faname" => "خاتم"),
			array("province_id" => 30, "enname" => "Mehriz", "faname" => "مهریز"),
			array("province_id" => 30, "enname" => "Meybod", "faname" => "میبد"),
			array("province_id" => 30, "enname" => "Taft", "faname" => "تفت"),
			array("province_id" => 30, "enname" => "Yazd", "faname" => "یزد"),

			array("province_id" => 31, "enname" => "Abhar", "faname" => "ابهر"),
			array("province_id" => 31, "enname" => "Ijrud", "faname" => "ایجرود"),
			array("province_id" => 31, "enname" => "Khodabandeh", "faname" => "خدابنده"),
			array("province_id" => 31, "enname" => "Khorramdarreh", "faname" => "خرمدره"),
			array("province_id" => 31, "enname" => "Mahneshan", "faname" => "ماهنشان"),
			array("province_id" => 31, "enname" => "Soltanieh", "faname" => "سلطانیه"),
			array("province_id" => 31, "enname" => "Tarom", "faname" => "طارم"),
			array("province_id" => 31, "enname" => "Zanjan", "faname" => "زنجان")
		);

        for ($i = 0; $i < count($data); $i++) {
            $data[$i]["created_at"] = $now;
            $data[$i]["updated_at"] = $now;
        }

     	City::insert($data);
    }
}
