CREATE TABLE states (
	id INTEGER NOT NULL PRIMARY KEY,

	enname VARCHAR(64) NOT NULL,
	faname VARCHAR(64) NOT NULL
);


CREATE TABLE cities (
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,

	state_id INTEGER NOT NULL,
	enname VARCHAR(64) NOT NULL,
	faname VARCHAR(64) NOT NULL,

	FOREIGN KEY(state_id) REFERENCES states(id)
);


INSERT INTO states(`id`, `enname`, `faname`) VALUES
	(1, "Alborz", "البرز"),
	(2, "Ardabil", "اردبیل"),
	(3, "Bushehr", "بوشهر"),
	(4, "Chaharmahal and Bakhtiari", "چهار محال و بختیاری"),
	(5, "East Azerbaijan", "آذربایجان شرقی"),
	(6, "Isfahan", "اصفهان"),
	(7, "Fars", "فارس"),
	(8, "Gilan", "گیلان"),
	(9, "Golestan", "گلستان"),
	(10, "Hamadan", "همدان"),
	(11, "Hormozgan", "هرمزگان"),
	(12, "Ilam", "ایلام"),
	(13, "Kerman", "کرمان"),
	(14, "Kermanshah", "کرمانشاه"),
	(15, "Khuzestan", "خوزستان"),
	(16, "Kohgiluyeh and Boyer Ahmad", "کهگیلویه و بویراحمد"),
	(17, "Kurdistan", "کردستان"),
	(18, "Lorestan", "لرستان"),
	(19, "Markazi", "مرکزی"),
	(20, "Mazandaran", "مازندران"),
	(21, "North Khorasan", "خراسان شمالی"),
	(22, "Qazvin", "قزوین"),
	(23, "Qom", "قم"),
	(24, "Razavi Khorasan", "خراسان رضوی"),
	(25, "Semnan", "سمنان"),
	(26, "Sistan and Baluchestan", "سیستان و بلوچستان"),
	(27, "South Khorasan", "خراسان جنوبی"),
	(28, "Tehran", "تهران"),
	(29, "West Azerbaijan", "آذربایجان غربی"),
	(30, "Yazd", "یزد"),
	(31, "Zanjan", "زنجان");


INSERT INTO cities(`state_id`, `enname`, `faname`) VALUES
	(1, "Eshtehard", "اشتهارد"),
	(1, "Fardis", "فردیس"),
	(1, "Karaj", "کرج"),
	(1, "Nazarabad", "نظرآباد"),
	(1, "Savojbolagh", "ساوجبلاغ"),
	(1, "Taleqan", "طالقان"),

	(2, "Ardabil", "اردبیل"),
	(2, "Bileh Savar", "بیله‌سوار"),
	(2, "Germi", "گرمی"),
	(2, "Khalkhal", "خلخال"),
	(2, "Kowsar", "کوثر"),
	(2, "Meshgin Shahr", "مشگین شهر"),
	(2, "Namin", "نمین"),
	(2, "Nir", "نیر"),
	(2, "Parsabad", "پارس‌آباد"),
	(2, "Sareyn", "سرعین"),

	(3, "Asaluyeh", "عسلویه"),
	(3, "Bushehr", "بوشهر"),
	(3, "Dashtestan", "دشتستان"),
	(3, "Dashti", "دشتی"),
	(3, "Deyr", "دیر"),
	(3, "Deylam", "دیلم"),
	(3, "Ganaveh", "گناوه"),
	(3, "Jam", "جم"),
	(3, "Kangan", "کنگان"),
	(3, "Tangestan", "تنگستان"),

	(4, "Ardal", "اردل"),
	(4, "Ben", "بن"),
	(4, "Borujen", "بروجن"),
	(4, "Farsan", "فارسان"),
	(4, "Kiar", "کیار"),
	(4, "Kuhrang", "کوهرنگ"),
	(4, "Lordegan", "لردگان"),
	(4, "Saman", "سامان"),
	(4, "Shahrekord", "شهرکرد"),

	(5, "Ahar", "اهر"),
	(5, "Ajab Shir", "عجب‌شیر"),
	(5, "Azarshahr", "آذرشهر"),
	(5, "Bonab", "بناب"),
	(5, "Bostanabad", "بستان‌آباد"),
	(5, "Charuymaq", "چاراویماق"),
	(5, "Heris", "هریس"),
	(5, "Hashtrud", "هشترود"),
	(5, "Jolfa", "جلفا"),
	(5, "Kaleybar", "کلیبر"),
	(5, "Khoda Afarin", "خداآفرین"),
	(5, "Malekan", "ملکان"),
	(5, "Maragheh", "مراغه"),
	(5, "Marand", "مرند"),
	(5, "Mianeh", "میانه"),
	(5, "Osku", "اسکو"),
	(5, "Sarab", "سراب"),
	(5, "Shabestar", "شبستر"),
	(5, "Tabriz", "تبریز"),
	(5, "Varzaqan", "ورزقان"),

	(6, "Aran and Bidgol", "آران و بیدگل"),
	(6, "Ardestan", "اردستان"),
	(6, "Borkhar", "برخوار"),
	(6, "Bouein and Miandasht", "بوئین و میاندشت"),
	(6, "Chadegan", "چادگان"),
	(6, "Dehaqan", "دهاقان"),
	(6, "Falavarjan", "فلاورجان"),
	(6, "Fereydan", "فریدن"),
	(6, "Fereydunshahr", "فریدون‌شهر"),
	(6, "Golpayegan", "گلپایگان"),
	(6, "Isfahan", "اصفهان"),
	(6, "Kashan", "کاشان"),
	(6, "Khour and Biabanak", "خور و بیابانک"),
	(6, "Khvansar", "خوانسار"),
	(6, "Khomeyni Shahr", "خمینی‌شهر"),
	(6, "Lenjan", "لنجان"),
	(6, "Mobarakeh", "مبارکه"),
	(6, "Nain", "نائین"),
	(6, "Najafabad", "نجف‌آباد"),
	(6, "Natanz", "نطنز"),
	(6, "Semirom", "سمیرم"),
	(6, "Shahreza", "شهرضا"),
	(6, "Shahin Shahr and Meymeh", "شاهین‌شهر و میمه"),
	(6, "Tiran and Karvan", "تیران و کرون"),

	(7, "Abadeh", "آباده"),
	(7, "Arsanjan", "ارسنجان"),
	(7, "Bavanat", "بوانات"),
	(7, "Darab", "داراب"),
	(7, "Eqlid", "اقلید"),
	(7, "Estahban", "استهبان"),
	(7, "Farashband", "فراشبند"),
	(7, "Fasa", "فسا"),
	(7, "Firuzabad", "فیروزآباد"),
	(7, "Gerash", "گراش"),
	(7, "Jahrom", "جهرم"),
	(7, "Kavar", "کوار"),
	(7, "Kazerun", "کازرون"),
	(7, "Kharameh", "خرامه"),
	(7, "Khonj", "خنج"),
	(7, "Khorrambid", "خرم‌بید"),
	(7, "Lamerd", "لامرد"),
	(7, "Larestan", "لارستان"),
	(7, "Mamasani", "ممسنی"),
	(7, "Marvdasht", "مرودشت"),
	(7, "Mohr", "مهر"),
	(7, "Neyriz", "نی ریز"),
	(7, "Pasargad", "پاسارگاد"),
	(7, "Qir and Karzin", "قیر و کارزین"),
	(7, "Rostam", "رستم"),
	(7, "Sarvestan", "سروستان"),
	(7, "Sepidan", "سپیدان"),
	(7, "Shiraz", "شیراز"),
	(7, "Zarrin Dasht", "زرین‌دشت"),

	(8, "Amlash", "املش"),
	(8, "Astara", "آستارا"),
	(8, "Astaneh ye Ashrafiyeh", "آستانه اشرفیه"),
	(8, "Bandar e Anzali", "بندر انزلی"),
	(8, "Fuman", "فومن"),
	(8, "Lahijan", "لاهیجان"),
	(8, "Langarud", "لنگرود"),
	(8, "Masal", "ماسال"),
	(8, "Rasht", "رشت"),
	(8, "Rezvanshahr", "رضوانشهر"),
	(8, "Rudbar", "رودبار"),
	(8, "Rudsar", "رودسر"),
	(8, "Shaft", "شفت"),
	(8, "Siahkal", "سیاهکل"),
	(8, "Sowme'eh Sara", "صومعه‌سرا"),
	(8, "Talesh", "طوالش"),

	(9, "Aliabad", "علی‌آباد"),
	(9, "Aqqala", "آق‌قلا"),
	(9, "Azadshahr", "آزادشهر"),
	(9, "Bandar e Gaz", "بندر گز"),
	(9, "Galikash", "گالیکش"),
	(9, "Gomishan", "گمیشان"),
	(9, "Gonbad e Kavus", "گنبد کاووس"),
	(9, "Gorgan", "گرگان"),
	(9, "Kalaleh", "کلاله"),
	(9, "Kordkuy", "کردکوی"),
	(9, "Maraveh Tappeh", "مراوه‌تپه"),
	(9, "Minudasht", "مینودشت"),
	(9, "Ramian", "رامیان"),
	(9, "Torkaman", "ترکمن"),

	(10, "Asadabad", "اسدآباد"),
	(10, "Bahar", "بهار"),
	(10, "Famenin", "فامنین"),
	(10, "Hamadan", "همدان"),
	(10, "Kabudarahang", "کبودرآهنگ"),
	(10, "Malayer", "ملایر"),
	(10, "Nahavand", "نهاوند"),
	(10, "Razan", "رزن"),
	(10, "Tuyserkan", "تویسرکان"),

	(11, "Abumusa", "ابوموسی"),
	(11, "Bandar Abbas", "بندرعباس"),
	(11, "Bandar Lengeh", "بندر لنگه"),
	(11, "Bashagard", "بشاگرد"),
	(11, "Bastak", "بستک"),
	(11, "Hajjiabad", "حاجی‌آباد"),
	(11, "Jask", "جاسک"),
	(11, "Khamir", "خمیر"),
	(11, "Minab", "میناب"),
	(11, "Parsian", "پارسیان"),
	(11, "Qeshm", "قشم"),
	(11, "Rudan", "رودان"),
	(11, "Sirik", "سیریک"),

	(12, "Abdanan", "آبدانان"),
	(12, "Badreh", "بدره"),
	(12, "Darreh Shahr", "دره‌شهر"),
	(12, "Dehloran", "دهلران"),
	(12, "Eyvan", "ایوان"),
	(12, "Ilam", "ایلام"),
	(12, "Malekshahi", "ملکشاهی"),
	(12, "Mehran", "مهران"),
	(12, "Chardavol", "چرداول"),
	(12, "Sirvan", "سیروان"),

	(13, "Anar", "انار"),
	(13, "Anbarabad", "عنبرآباد"),
	(13, "Arzuiyeh", "ارزوئیه"),
	(13, "Baft", "بافت"),
	(13, "Bam", "بم"),
	(13, "Bardsir", "بردسیر"),
	(13, "Fahraj", "فهرج"),
	(13, "Faryab", "فاریاب"),
	(13, "Jiroft", "جیرفت"),
	(13, "Kahnuj", "کهنوج"),
	(13, "Kerman", "کرمان"),
	(13, "Kuhbanan", "کوهبنان"),
	(13, "Manujan", "منوجان"),
	(13, "Narmashir", "نرماشیر"),
	(13, "Qaleh Ganj", "قلعه گنج"),
	(13, "Rabor", "رابر"),
	(13, "Rafsanjan", "رفسنجان"),
	(13, "Ravar", "راور"),
	(13, "Rigan", "ریگان"),
	(13, "Rudbar e Jonubi", "رودبار جنوب"),
	(13, "Shahr e Babak", "شهربابک"),
	(13, "Sirjan", "سیرجان"),
	(13, "Zarand", "زرند"),

	(14, "Dalahu", "دالاهو"),
	(14, "Eslamabad e Gharb", "اسلام‌آباد غرب"),
	(14, "Gilan e Gharb", "گیلانغرب"),
	(14, "Harsin", "هرسین"),
	(14, "Javanrud", "جوانرود"),
	(14, "Kangavar", "کنگاور"),
	(14, "Kermanshah", "کرمانشاه"),
	(14, "Paveh", "پاوه"),
	(14, "Qasr e Shirin", "قصرشیرین"),
	(14, "Ravansar", "روانسر"),
	(14, "Sahneh", "صحنه"),
	(14, "Sarpol e Zahab", "سرپل ذهاب"),
	(14, "Salas e Babajani", "ثلاث باباجانی"),
	(14, "Sonqor", "سنقر"),

	(15, "Abadan", "آبادان"),
	(15, "Aghajari", "آغاجاری"),
	(15, "Ahvaz", "اهواز"),
	(15, "Andika", "اندیکا"),
	(15, "Andimeshk", "اندیمشک"),
	(15, "Bagh e Malek", "باغ‌ملک"),
	(15, "Bavi", "باوی"),
	(15, "Behbahan", "بهبهان"),
	(15, "Dasht e Azadegan", "دشت آزادگان"),
	(15, "Dezful", "دزفول"),
	(15, "Gotvand", "گتوند"),
	(15, "Haftkel", "هفتکل"),
	(15, "Hamidieh", "حمیدیه"),
	(15, "Hendijan", "هندیجان"),
	(15, "Hoveyzeh", "هویزه"),
	(15, "Izeh", "ایذه"),
	(15, "Karun", "کارون"),
	(15, "Khorramshahr", "خرمشهر"),
	(15, "Lali", "لالی"),
	(15, "Mahshahr", "ماهشهر"),
	(15, "Masjed Soleyman", "مسجدسلیمان"),
	(15, "Omidiyeh", "امیدیه"),
	(15, "Ramhormoz", "رامهرمز"),
	(15, "Ramshir", "رامشیر"),
	(15, "Shadegan", "شادگان"),
	(15, "Shush", "شوش"),
	(15, "Shushtar", "شوشتر"),

	(16, "Basht", "باشت"),
	(16, "Bahmai", "بهمئی"),
	(16, "Boyer Ahmad", "بویراحمد"),
	(16, "Charam", "چرام"),
	(16, "Dana", "دنا"),
	(16, "Gachsaran", "گچساران"),
	(16, "Kohgiluyeh", "کهگیلویه"),
	(16, "Landeh", "لنده"),

	(17, "Baneh", "بانه"),
	(17, "Bijar", "بیجار"),
	(17, "Dehgolan", "دهگلان"),
	(17, "Divandarreh", "دیواندره"),
	(17, "Kamyaran", "کامیاران"),
	(17, "Marivan", "مریوان"),
	(17, "Qorveh", "قروه"),
	(17, "Sanandaj", "سنندج"),
	(17, "Saqqez", "سقز"),
	(17, "Sarvabad", "سروآباد"),

	(18, "Aligudarz", "الیگودرز"),
	(18, "Azna", "ازنا"),
	(18, "Borujerd", "بروجرد"),
	(18, "Delfan", "دلفان"),
	(18, "Dorud", "دورود"),
	(18, "Dowreh", "دوره"),
	(18, "Khorramabad", "خرم‌آباد"),
	(18, "Kuhdasht", "کوهدشت"),
	(18, "Pol e Dokhtar", "پلدختر"),
	(18, "Rumeshkan", "رومشکان"),
	(18, "Selseleh", "سلسله"),

	(19, "Ashtian", "آشتیان"),
	(19, "Arak", "اراک"),
	(19, "Delijan", "دلیجان"),
	(19, "Farahan", "فراهان"),
	(19, "Khomeyn", "خمین"),
	(19, "Khondab", "خنداب"),
	(19, "Komijan", "کمیجان"),
	(19, "Mahallat", "محلات"),
	(19, "Saveh", "ساوه"),
	(19, "Shazand", "شازند"),
	(19, "Tafresh", "تفرش"),
	(19, "Zarandieh", "زرندیه"),

	(20, "Abbasabad", "عباس‌آباد"),
	(20, "Amol", "آمل"),
	(20, "Babol", "بابل"),
	(20, "Babolsar", "بابلسر"),
	(20, "Behshahr", "بهشهر"),
	(20, "Chalus", "چالوس"),
	(20, "Fereydunkenar", "فریدونکنار"),
	(20, "Galugah", "گلوگاه"),
	(20, "Juybar", "جویبار"),
	(20, "Kelardasht", "کلاردشت"),
	(20, "Mahmudabad", "محمودآباد"),
	(20, "Miandorud", "میاندرود"),
	(20, "Neka", "نکا"),
	(20, "Nowshahr", "نوشهر"),
	(20, "Nur", "نور"),
	(20, "Qaem Shahr", "قائم‌شهر"),
	(20, "Ramsar", "رامسر"),
	(20, "Sari", "ساری"),
	(20, "Simorgh", "سیمرغ"),
	(20, "North Savadkuh", "سوادکوه"),
	(20, "Savadkuh", "سوادکوه شمالی"),
	(20, "Tonekabon", "تنکابن"),

	(21, "Bojnord", "بجنورد"),
	(21, "Esfarayen", "اسفراین"),
	(21, "Faruj", "فاروج"),
	(21, "Garmeh", "گرمه"),
	(21, "Jajarm", "جاجرم"),
	(21, "Maneh and Samalqan", "مانه و سملقان"),
	(21, "Raz and Jargalan", "راز و جرگلان"),
	(21, "Shirvan", "شیروان"),

	(22, "Abyek", "آبیک"),
	(22, "Avaj", "آوج"),
	(22, "Alborz", "البرز"),
	(22, "Buin Zahra", "بوئین‌زهرا"),
	(22, "Qazvin", "قزوین"),
	(22, "Takestan", "تاکستان"),

	(23, "Qom", "قم"),

	(24, "Bajestan", "بجستان"),
	(24, "Bakharz", "باخرز"),
	(24, "Bardaskan", "بردسکن"),
	(24, "Chenaran", "چناران"),
	(24, "Dargaz", "درگز"),
	(24, "Davarzan", "داورزن"),
	(24, "Fariman", "فریمان"),
	(24, "Firuzeh", "فیروزه"),
	(24, "Gonabad", "گناباد"),
	(24, "Jowayin", "جوین"),
	(24, "Joghatai", "جغتای"),
	(24, "Kalat", "کلات"),
	(24, "Kashmar", "کاشمر"),
	(24, "Khaf", "خواف"),
	(24, "Khalilabad", "خلیل‌آباد"),
	(24, "Khoshab", "خوشاب"),
	(24, "Mahvelat", "مه‌ولات"),
	(24, "Mashhad", "مشهد"),
	(24, "Nishapur", "نیشابور"),
	(24, "Quchan", "قوچان"),
	(24, "Roshtkhar", "رشتخوار"),
	(24, "Sabzevar", "سبزوار"),
	(24, "Sarakhs", "سرخس"),
	(24, "Taybad", "تایباد"),
	(24, "Binalud", "بینالود"),
	(24, "Torbat e Jam", "تربت جام"),
	(24, "Torbat e Heydarieh", "تربت حیدریه"),
	(24, "Zaveh", "زاوه"),

	(25, "Aradan", "آرادان"),
	(25, "Damghan", "دامغان"),
	(25, "Garmsar", "گرمسار"),
	(25, "Mehdishahr", "مهدی‌شهر"),
	(25, "Meyami", "میامی"),
	(25, "Semnan", "سمنان"),
	(25, "Shahrud", "شاهرود"),
	(25, "Sorkheh", "سرخه"),

	(26, "Chabahar", "چابهار"),
	(26, "Dalgan", "دلگان"),
	(26, "Fanuj", "فنوج"),
	(26, "Hamun", "هامون"),
	(26, "Hirmand", "هیرمند"),
	(26, "Iranshahr", "ایرانشهر"),
	(26, "Khash", "خاش"),
	(26, "Konarak", "کنارک"),
	(26, "Mehrestan", "مهرستان"),
	(26, "Mirjaveh", "میرجاوه"),
	(26, "Nik Shahr", "نیک شهر"),
	(26, "Nimruz", "نیمروز"),
	(26, "Qasr e Qand", "قصرقند"),
	(26, "Saravan", "سراوان"),
	(26, "Sarbaz", "سرباز"),
	(26, "Sib and Suran", "سیب و سوران"),
	(26, "Zabol", "زابل"),
	(26, "Zahedan", "زاهدان"),
	(26, "Zehak", "زهک"),

	(27, "Birjand", "بیرجند"),
	(27, "Boshruyeh", "بشرویه"),
	(27, "Darmian", "درمیان"),
	(27, "Ferdows", "فردوس"),
	(27, "Khusf", "خوسف"),
	(27, "Nehbandan", "نهبندان"),
	(27, "Qaenat", "قائنات"),
	(27, "Sarayan", "سرایان"),
	(27, "Sarbisheh", "سربیشه"),
	(27, "Tabas", "طبس"),
	(27, "Zirkuh", "زیرکوه"),

	(28, "Baharestan", "بهارستان"),
	(28, "Damavand", "دماوند"),
	(28, "Eslamshahr", "اسلامشهر"),
	(28, "Firuzkuh", "فیروزکوه"),
	(28, "Malard", "ملارد"),
	(28, "Pakdasht", "پاکدشت"),
	(28, "Pardis", "پردیس"),
	(28, "Pishva", "پیشوا"),
	(28, "Robat Karim", "رباط‌کریم"),
	(28, "Rey", "ری"),
	(28, "Shemiranat", "شمیرانات"),
	(28, "Shahriar", "شهریار"),
	(28, "Qarchak", "قرچک"),
	(28, "Qods", "قدس"),
	(28, "Tehran", "تهران"),
	(28, "Varamin", "ورامین"),

	(29, "Bukan", "بوکان"),
	(29, "Chaldoran", "چالدران"),
	(29, "Chaypareh", "چایپاره"),
	(29, "Khoy", "خوی"),
	(29, "Mahabad", "مهاباد"),
	(29, "Maku", "ماکو"),
	(29, "Miandoab", "میاندوآب"),
	(29, "Naqadeh", "نقده"),
	(29, "Oshnavieh", "اشنویه"),
	(29, "Piranshahr", "پیرانشهر"),
	(29, "Poldasht", "پلدشت"),
	(29, "Salmas", "سلماس"),
	(29, "Sardasht", "سردشت"),
	(29, "Shahin Dezh", "شاهین‌دژ"),
	(29, "Showt", "شوط"),
	(29, "Takab", "تکاب"),
	(29, "Urmia", "ارومیه"),

	(30, "Abarkuh", "ابرکوه"),
	(30, "Ardakan", "اردکان"),
	(30, "Ashkezar", "اشکذر"),
	(30, "Bafq", "بافق"),
	(30, "Behabad", "بهاباد"),
	(30, "Khatam", "خاتم"),
	(30, "Mehriz", "مهریز"),
	(30, "Meybod", "میبد"),
	(30, "Taft", "تفت"),
	(30, "Yazd", "یزد"),

	(31, "Abhar", "ابهر"),
	(31, "Ijrud", "ایجرود"),
	(31, "Khodabandeh", "خدابنده"),
	(31, "Khorramdarreh", "خرمدره"),
	(31, "Mahneshan", "ماهنشان"),
	(31, "Soltanieh", "سلطانیه"),
	(31, "Tarom", "طارم"),
	(31, "Zanjan", "زنجان");
